raw_data_path: /nas/ilahia/dataset
target_path: /nas/ilahia/dataset/cache
output_path: /nas/ilahia/dataset/output
output_id: greater_jakarta_1pct

input_downsampling: 0.1
java_memory: 300G
threads: 48
hdm_threads: 4
stages:
    #- data.census.cleaned
    #- data.hts.cleaned
             #- data.Opportunities.extract_roads_osm
    #- population.matching
    #- population.upscaled
    #- population.sociodemographics
    #- population.trips
    #- population.activities
    #- data.spatial.zones
    #- data.od.cleaned
    #- population.opportunities
    #- population.spatial.by_person.primary_zones
    #- population.spatial.by_person.primary_locations
    #- population.spatial.by_person.output
    - population.spatial.locations
    - matsim.facilities
    - matsim.population
    - matsim.households
    #- matsim.java.eqasim
    - matsim.secondary_locations
    #- analysis.distance
    #- utils.java
    - matsim.run
   
